spring.datasource.url=jdbc:postgresql://localhost:5432/udtracker_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
steam.api.key=1412FCE746583132B2734909F9F4D663
faceit.api.key=7842e240-e2bf-43b3-b5dd-2e828bc4b774